[build]
builder = "nixpacks"
buildCommand = "npm install"
runCommand = "npm start"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/system/status"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[[services]]
name = "mduc-api"
port = 3000
protocol = "tcp"
autostart = true
concurrency = 10

[env]
NODE_ENV = "production"
PORT = "3000"
